kind: pipeline
type: docker

trigger:
  branch:
    - main

steps:

- name: get submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: Build with Hugo
  image: klakegg/hugo:0.92.1-alpine
  commands:
  - hugo version
  - hugo --destination /drone/src/build

- name: "Docker build & push"
  image: plugins/docker
  settings:
    repo: electron2302/sart-blog
    username: electron2302
    password:
      from_secret: dockerhub_password
    dockerfile: Dockerfile