kind: pipeline
type: docker

steps:

- name: get submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: Build with Hugo
  image: klakegg/hugo:0.92.1-alpine
  commands:
  - hugo version
  - hugo --destination /drone/src/build
#  - minify -r -o /drone/src/build /drone/src/build

- name: list 
  image: alpine
  commands:
  - apk add --update tree
  - tree
